blank_issues_enabled: false
contact_links:
  - name: GitHub Docs
    url: https://docs.github.com/issues/tracking-your-work-with-issues/creating-an-issue
    about: Learn more about creating and managing GitHub issues.
